/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yixitongda_myapplication_Fileutils */

#ifndef _Included_com_yixitongda_myapplication_Fileutils
#define _Included_com_yixitongda_myapplication_Fileutils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yixitongda_myapplication_Fileutils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_yixitongda_myapplication_Fileutils_diff
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
